<h1>LIVE STREAM OUTPUT HERE</h1>

<video id="player" class="video-js vjs-default-skin" height="360" width="640" controls preload="none" >
</video>
<script>
    require(['jquery', 'Aeshel_Livestream/js/videojs'], function(jQuery){
        var player = videojs('#player');
        player.src({
            src: '<?php echo $block->getStreamSource(); ?>',
            type: 'application/x-mpegURL'
        });
    });
</script>
