<h1>LIVE STREAM OUTPUT HERE</h1>

<video id="player" class="video-js vjs-default-skin" height="360" width="640" controls preload="none" >
    <source src="https://192.168.0.106:8080/hls/test.m3u8" type="application/x-mpegURL" />
</video>
<script>
    require(['jquery', 'Aeshel_Livestream/js/videojs'], function(jQuery){
        var player = videojs('#player');
        player.src({
            src: 'http://192.168.0.106:8080/hls/test.m3u8',
            type: 'application/x-mpegURL'
        });
    });
</script>

